
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 08 17:03:14 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXLEQ = 32;
  public static final int CHAR = 46;
  public static final int CONST = 6;
  public static final int GRT = 33;
  public static final int GRTEQ = 34;
  public static final int LPAREN = 21;
  public static final int SEMI = 20;
  public static final int CONTINUE = 15;
  public static final int LSS = 35;
  public static final int MINUS = 27;
  public static final int STAR = 28;
  public static final int RPAREN = 22;
  public static final int LSSEQ = 36;
  public static final int DBLEQ = 31;
  public static final int BOOL = 45;
  public static final int COMMA = 39;
  public static final int CLASS = 4;
  public static final int PERC = 30;
  public static final int PLUS = 26;
  public static final int IF = 7;
  public static final int LSQUAREBR = 23;
  public static final int DOT = 25;
  public static final int FINDANY = 17;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 40;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int NUMBER = 43;
  public static final int IDENT = 44;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int FOREACH = 16;
  public static final int DBLAMP = 37;
  public static final int LBRACE = 18;
  public static final int ELSE = 5;
  public static final int READ = 11;
  public static final int WHILE = 8;
  public static final int RBRACE = 19;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int DBLPLUS = 41;
  public static final int DBLVER = 38;
  public static final int FWDSLASH = 29;
  public static final int DBLMINUS = 42;
  public static final int RSQUAREBR = 24;
  public static final int PRINT = 10;
}

