
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 12 00:24:27 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXLEQ = 33;
  public static final int CHAR = 48;
  public static final int CONST = 6;
  public static final int NAMESPACE = 18;
  public static final int GRTEQ = 35;
  public static final int GRT = 34;
  public static final int LPAREN = 22;
  public static final int SEMI = 21;
  public static final int CONTINUE = 15;
  public static final int LSS = 36;
  public static final int MINUS = 28;
  public static final int STAR = 29;
  public static final int RPAREN = 23;
  public static final int LSSEQ = 37;
  public static final int DBLEQ = 32;
  public static final int BOOL = 47;
  public static final int COMMA = 40;
  public static final int CLASS = 4;
  public static final int PERC = 31;
  public static final int DBLCOLON = 44;
  public static final int PLUS = 27;
  public static final int IF = 7;
  public static final int LSQUAREBR = 24;
  public static final int DOT = 26;
  public static final int FINDANY = 17;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 41;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int NUMBER = 45;
  public static final int IDENT = 46;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int FOREACH = 16;
  public static final int DBLAMP = 38;
  public static final int LBRACE = 19;
  public static final int ELSE = 5;
  public static final int READ = 11;
  public static final int WHILE = 8;
  public static final int RBRACE = 20;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int DBLPLUS = 42;
  public static final int DBLVER = 39;
  public static final int FWDSLASH = 30;
  public static final int DBLMINUS = 43;
  public static final int RSQUAREBR = 25;
  public static final int PRINT = 10;
}

