
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Feb 09 00:08:48 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXLEQ = 30;
  public static final int CHAR = 44;
  public static final int CONST = 6;
  public static final int GRT = 31;
  public static final int GRTEQ = 32;
  public static final int LPAREN = 20;
  public static final int SEMI = 19;
  public static final int CONTINUE = 15;
  public static final int LSS = 33;
  public static final int MINUS = 25;
  public static final int STAR = 26;
  public static final int RPAREN = 21;
  public static final int LSSEQ = 34;
  public static final int DBLEQ = 29;
  public static final int BOOL = 43;
  public static final int COMMA = 37;
  public static final int CLASS = 4;
  public static final int PERC = 28;
  public static final int PLUS = 24;
  public static final int IF = 7;
  public static final int LSQUAREBR = 22;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 38;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int NUMBER = 41;
  public static final int IDENT = 42;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int FOREACH = 16;
  public static final int DBLAMP = 35;
  public static final int LBRACE = 17;
  public static final int ELSE = 5;
  public static final int READ = 11;
  public static final int WHILE = 8;
  public static final int RBRACE = 18;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int DBLPLUS = 39;
  public static final int DBLVER = 36;
  public static final int FWDSLASH = 27;
  public static final int DBLMINUS = 40;
  public static final int RSQUAREBR = 23;
  public static final int PRINT = 10;
}

